<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.anand.leetcode</groupId>
    <artifactId>leetcode-solutions</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>arrays</module>
        <module>binary-search</module>
        <module>contest/weekly-contest-494/q1-construct-uniform-parity-array-i</module>
        <module>dynamic-programming/1594-maximum-non-negative-product-in-a-matrix</module>
        <module>greedy/55-jump-game</module>
        <module>greedy/meeting-rooms</module>
        <module>matrix/1886-determine-whether-matrix-can-be-obtained-by-rotation</module>
        <module>linked-list</module>
        <module>leetcode-75/1768-merge-strings-alternately</module>
        <module>leetcode-75/1071-greatest-common-divisor-of-strings</module>
        <module>leetcode-75/1431-kids-with-the-greatest-number-of-candies</module>
        <module>leetcode-75/605-can-place-flowers</module>
        <module>leetcode-75/345-reverse-vowels-of-a-string</module>
        <module>leetcode-75/151-reverse-words-in-a-string</module>
        <module>leetcode-75/238-product-of-array-except-self</module>
        <module>leetcode-75/283-move-zeroes</module>
        <module>leetcode-75/643-maximum-average-subarray-i</module>
        <module>leetcode-75/1732-find-the-highest-altitude</module>
        <module>leetcode-75/724-find-pivot-index</module>
        <module>leetcode-75/1207-unique-number-of-occurrences</module>
        <module>leetcode-75/933-number-of-recent-calls</module>
        <module>leetcode-75/443-string-compression</module>
        <module>leetcode-75/2095-delete-the-middle-node-of-a-linked-list</module>
        <module>leetcode-75/739-daily-temperatures</module>
        <module>leetcode-75/328-odd-even-linked-list</module>
        <module>leetcode-75/215-kth-largest-element-in-an-array</module>
        <module>daily-question/2540-minimum-common-value</module>
        <module>RestAPI</module>
        <module>strings/3-longest-substring-without-repeating-characters</module>
        <module>contest/biweekly-contest-183/q1</module>
        <module>contest/biweekly-contest-183/q2</module>
        <module>contest/biweekly-contest-183/q3</module>
        <module>contest/biweekly-contest-183/q4</module>
    </modules>
</project>
